# F5-TTS Base config for RunPod training
# Architecture MUST match pretrained_model.safetensors weights
# Only optim/dataset/ckpts params should be overridden via env vars

hydra:
  run:
    dir: ckpts/runpod_default

datasets:
  name: kokoro_libri
  batch_size_per_gpu: 5000
  batch_size_type: frame
  max_samples: 32
  num_workers: 8

optim:
  epochs: 8
  learning_rate: 1e-5
  num_warmup_updates: 50
  grad_accumulation_steps: 1
  max_grad_norm: 1.0
  bnb_optimizer: false

model:
  name: F5TTS_Base
  tokenizer: pinyin
  tokenizer_path: null
  backbone: DiT
  arch:
    dim: 1024
    depth: 22
    heads: 16
    ff_mult: 2
    text_dim: 512
    text_mask_padding: false   # CRITICAL - must be false for pretrained weights
    conv_layers: 4
    pe_attn_head: 1            # CRITICAL - must be 1 for pretrained weights
    attn_backend: torch
    attn_mask_enabled: false
    checkpoint_activations: false
  mel_spec:
    target_sample_rate: 24000
    n_mel_channels: 100
    hop_length: 256
    win_length: 1024
    n_fft: 1024
    mel_spec_type: vocos
  vocoder:
    is_local: false
    local_path: null

ckpts:
  logger: tensorboard
  log_samples: false
  save_per_updates: 500
  keep_last_n_checkpoints: 3
  last_per_updates: 200
  save_dir: ckpts/runpod_default
